version: '3.8'

services:
  mcp-lib-foo:
    build:
      context: ../..
      dockerfile: packages/mcp-lib-foo/Dockerfile
    image: mcp-lib-foo:latest
    container_name: mcp-lib-foo-server
    restart: unless-stopped
    environment:
      - NODE_ENV=development
      - MCP_SERVER_NAME=mcp-lib-foo
      - MCP_SERVER_VERSION=0.0.0
      - LOG_LEVEL=info
    ports:
      - "3010:3000"
    volumes:
      # For development - mount source code
      - ./src:/app/src:ro
      - ./dist:/app/dist:ro
    networks:
      - mcp-network
    healthcheck:
      test: ["CMD", "node", "-e", "process.exit(0)"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 10s
    labels:
      - "com.example.description=MCP Server for lib-foo"
      - "com.example.version=0.0.0"

  # Optional: Add a test container for integration testing
  mcp-lib-foo-test:
    build:
      context: ../..
      dockerfile: packages/mcp-lib-foo/Dockerfile
      target: build
    container_name: mcp-lib-foo-test
    command: ["pnpm", "test"]
    environment:
      - NODE_ENV=test
    volumes:
      - ./src:/app/packages/mcp-lib-foo/src:ro
      - ./features:/app/packages/mcp-lib-foo/features:ro
    networks:
      - mcp-network
    profiles:
      - test

networks:
  mcp-network:
    driver: bridge
    name: mcp-network

volumes:
  mcp-data:
    driver: local