name: Cleanup After PR Merge

on:
  pull_request:
    types: [closed]

jobs:
  cleanup-branch:
    runs-on: ubuntu-latest
    # Only run if PR was merged (not just closed)
    if: github.event.pull_request.merged == true

    permissions:
      contents: write
      pull-requests: read
      issues: write

    steps:
      - name: Delete merged branch
        run: |
          # Extract branch name from PR
          BRANCH_NAME="${{ github.event.pull_request.head.ref }}"

          echo "🗑️ Deleting merged branch: $BRANCH_NAME"

          # Delete the branch (if it's not main/master)
          if [[ "$BRANCH_NAME" != "main" && "$BRANCH_NAME" != "master" ]]; then
            curl -X DELETE \
              -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
              -H "Accept: application/vnd.github.v3+json" \
              "https://api.github.com/repos/${{ github.repository }}/git/refs/heads/$BRANCH_NAME" || true
            echo "✅ Branch deleted successfully"
          else
            echo "⚠️ Skipped deleting protected branch: $BRANCH_NAME"
          fi

      - name: Add merge comment to linked issues
        run: |
          # Extract issue numbers from PR body using regex
          PR_BODY="${{ github.event.pull_request.body }}"

          # Find all "Closes #123" or "Fixes #123" patterns
          ISSUE_NUMBERS=$(echo "$PR_BODY" | grep -oiE "(closes|fixes|resolves) #([0-9]+)" | grep -oE "[0-9]+" || true)

          if [ -n "$ISSUE_NUMBERS" ]; then
            for ISSUE_NUMBER in $ISSUE_NUMBERS; do
              echo "💬 Adding merge comment to issue #$ISSUE_NUMBER"

              curl -X POST \
                -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                -H "Accept: application/vnd.github.v3+json" \
                "https://api.github.com/repos/${{ github.repository }}/issues/$ISSUE_NUMBER/comments" \
                -d "{\"body\":\"🎉 **Issue completed!**\\n\\n✅ Pull Request merged: ${{ github.event.pull_request.html_url }}\\n✅ Branch \`${{ github.event.pull_request.head.ref }}\` deleted\\n\\nThis issue has been resolved and the associated branch has been cleaned up.\"}" || true

              echo "✅ Comment added to issue #$ISSUE_NUMBER"
            done
          else
            echo "ℹ️ No linked issues found in PR body"
          fi

      - name: Cleanup issue tracking files
        run: |
          # If there are issue tracking files, we could clean them up
          # This would require checking out the repo first
          echo "🧹 Issue tracking files will be cleaned up in future commits"